### ISSUE TITLE
Community Page

### ISSUE THREAD

**Issue by SteveLasker** [scitt-community/scitt-web#23]
Create a community page:

- How to get involved with IETF & SCITT
- SCITT regular meetings
- SCITT on the IETF Email lists
- SCITT on Slack

**Comment by DHRUVKHANDELWAL00** [comment]
hey @SteveLasker ,can u elaborate more on this issue

**Comment by SteveLasker** [comment]
Hi @DHRUVKHANDELWAL00, welcome to the SCITT community.

We'd like to host a page that provides insight into how folks can get involved. The page would incorporate the topics above.
Some examples:
- [Helm Community](https://github.com/helm/community#how-can-i-help)
- [ORAS Community](https://oras.land/community/)

**Comment by aj-stein-nist** [comment]
I am willing to pick this up if no maintainer objects.
